-- MySQL Workbench Synchronization
-- Generated: 2026-06-13 15:43
-- Model: New Model
-- Version: 1.0
-- Project: FERB
-- Author: Mohamed Fayed

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='PIPES_AS_CONCAT';

ALTER TABLE `Elecon`.`EMPLOYEE_JOB_HISTORY`
ADD COLUMN `proj_id` INT(11) NULL DEFAULT NULL AFTER `to_dt`,
ADD COLUMN `version_no` INT(11) NULL DEFAULT NULL AFTER `proj_id`,
ADD INDEX `fk_EMPLOYEE_JOB_HISTORY_PROJECTS_MAST1_idx` (`proj_id` ASC, `version_no` ASC);
;

DROP TABLE IF EXISTS `Elecon`.`PROJECT_ASSIGNMENTS` ;

ALTER TABLE `Elecon`.`EMPLOYEE_JOB_HISTORY`
ADD CONSTRAINT `fk_EMPLOYEE_JOB_HISTORY_PROJECTS_MAST1`
  FOREIGN KEY (`proj_id` , `version_no`)
  REFERENCES `Elecon`.`PROJECTS_MAST` (`proj_id` , `version_no`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

ALTER TABLE EMPLOYEE_JOB_HISTORY
MODIFY frm_dt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE `Elecon`.`EMPLOYEE_JOB_HISTORY`
CHANGE COLUMN `seq` `seq` INT(11) NOT NULL AUTO_INCREMENT ;

