package com.aalm.pm.model;

import com.aalm.pm.model.common.AalmPm;

import java.sql.CallableStatement;
import java.sql.SQLException;

import oracle.jbo.JboException;
import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.DBTransactionImpl;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jun 10 08:38:50 EEST 2026
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AalmPmImpl extends ApplicationModuleImpl implements AalmPm {
    /**
     * This is the default constructor (do not remove).
     */
    public AalmPmImpl() {
    }
/* delete project from PROJECT_MAST */
        public void delete_project(int pProjId){
        DBTransactionImpl dbti = (DBTransactionImpl) getDBTransaction();
        CallableStatement stmnt = dbti.createCallableStatement(("delete from PROJECTS_MAST WHERE proj_id = ? and version_no = 0;"), 0);
        try {
            stmnt.setInt(1, pProjId);
            stmnt.execute();
            executeCommand("Commit");
//            System.out.println("creation done.++++++++");
        }catch (SQLException sqlerr) {
//            System.out.println(" This is not done--------");
            throw new JboException(sqlerr);
        } finally {
            try {
                if (stmnt != null) {
                    stmnt.close();
                }
            } catch (SQLException closeerr) {
                throw new JboException(closeerr);
            }
        } 
    }
    /**
     * Container's getter for ClientsV.
     * @return ClientsV
     */
    public ViewObjectImpl getClientsV() {
        return (ViewObjectImpl) findViewObject("ClientsV");
    }

    /**
     * Container's getter for ProjectSectionItemsV.
     * @return ProjectSectionItemsV
     */
    public ViewObjectImpl getProjectSectionItemsV() {
        return (ViewObjectImpl) findViewObject("ProjectSectionItemsV");
    }

    /**
     * Container's getter for ProjectSectionSubItemsV.
     * @return ProjectSectionSubItemsV
     */
    public ViewObjectImpl getProjectSectionSubItemsV() {
        return (ViewObjectImpl) findViewObject("ProjectSectionSubItemsV");
    }

    /**
     * Container's getter for ItemsListRo.
     * @return ItemsListRo
     */
    public ViewObjectImpl getItemsListRo() {
        return (ViewObjectImpl) findViewObject("ItemsListRo");
    }

    /**
     * Container's getter for ProjectMastV.
     * @return ProjectMastV
     */
    public ViewObjectImpl getProjectMastV() {
        return (ViewObjectImpl) findViewObject("ProjectMastV");
    }

    /**
     * Container's getter for ProjectSectionsV.
     * @return ProjectSectionsV
     */
    public ViewObjectImpl getProjectSectionsV() {
        return (ViewObjectImpl) findViewObject("ProjectSectionsV");
    }

    /**
     * Container's getter for ProjectStaffTreeV.
     * @return ProjectStaffTreeV
     */
    public ViewObjectImpl getProjectStaffTreeV() {
        return (ViewObjectImpl) findViewObject("ProjectStaffTreeV");
    }

    /**
     * Container's getter for ProjectStaffV.
     * @return ProjectStaffV
     */
    public ViewObjectImpl getProjectStaffV() {
        return (ViewObjectImpl) findViewObject("ProjectStaffV");
    }

    /**
     * Container's getter for ProjectsListV.
     * @return ProjectsListV
     */
    public ViewObjectImpl getProjectsListV() {
        return (ViewObjectImpl) findViewObject("ProjectsListV");
    }

    /**
     * Container's getter for ProjectVersionsV.
     * @return ProjectVersionsV
     */
    public ViewObjectImpl getProjectVersionsV() {
        return (ViewObjectImpl) findViewObject("ProjectVersionsV");
    }

    /**
     * Container's getter for FkProjectSectionItemsProjectSectionItems1VL1.
     * @return FkProjectSectionItemsProjectSectionItems1VL1
     */
    public ViewLinkImpl getFkProjectSectionItemsProjectSectionItems1VL1() {
        return (ViewLinkImpl) findViewLink("FkProjectSectionItemsProjectSectionItems1VL1");
    }

    /**
     * Container's getter for FkProjectSectionProjectsMast1VL1.
     * @return FkProjectSectionProjectsMast1VL1
     */
    public ViewLinkImpl getFkProjectSectionProjectsMast1VL1() {
        return (ViewLinkImpl) findViewLink("FkProjectSectionProjectsMast1VL1");
    }

    /**
     * Container's getter for ProjectStaffTreeSelfJoinCVL1.
     * @return ProjectStaffTreeSelfJoinCVL1
     */
    public ViewLinkImpl getProjectStaffTreeSelfJoinCVL1() {
        return (ViewLinkImpl) findViewLink("ProjectStaffTreeSelfJoinCVL1");
    }

    /**
     * Container's getter for ProjectListToProjectVersionsCL1.
     * @return ProjectListToProjectVersionsCL1
     */
    public ViewLinkImpl getProjectListToProjectVersionsCL1() {
        return (ViewLinkImpl) findViewLink("ProjectListToProjectVersionsCL1");
    }
}

