package com.aalm.hr.model.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Oct 24 19:36:58 EET 2025
// ---------------------------------------------------------------------
public interface AalmHr extends ApplicationModule {
    void sp_handle_approval_action(int p_trans_id, int p_detail_id, String p_action, String p_comments);

    void sp_create_approval_transaction(int p_cycle_type_id, int p_transaction_ref_id, int p_requested_by,
                                        int p_org_code);

    void createTodayAttendanceIfMissing(int userId);
}

