package com.aalm.center.model.views;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sat May 18 13:10:57 EEST 2024
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ItemsToBeSelectedInAssImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public ItemsToBeSelectedInAssImpl() {
    }

    /**
     * Returns the bind variable value for pItemCode.
     * @return bind variable value for pItemCode
     */
    public String getpItemCode() {
        return (String) getNamedWhereClauseParam("pItemCode");
    }

    /**
     * Sets <code>value</code> for bind variable pItemCode.
     * @param value value to bind as pItemCode
     */
    public void setpItemCode(String value) {
        setNamedWhereClauseParam("pItemCode", value);
    }

    /**
     * Returns the bind variable value for pAssCode.
     * @return bind variable value for pAssCode
     */
    public String getpAssCode() {
        return (String) getNamedWhereClauseParam("pAssCode");
    }

    /**
     * Sets <code>value</code> for bind variable pAssCode.
     * @param value value to bind as pAssCode
     */
    public void setpAssCode(String value) {
        setNamedWhereClauseParam("pAssCode", value);
    }

    /**
     * Returns the bind variable value for pPrntAsmblies.
     * @return bind variable value for pPrntAsmblies
     */
    public String getpPrntAsmblies() {
        return (String) getNamedWhereClauseParam("pPrntAsmblies");
    }

    /**
     * Sets <code>value</code> for bind variable pPrntAsmblies.
     * @param value value to bind as pPrntAsmblies
     */
    public void setpPrntAsmblies(String value) {
        setNamedWhereClauseParam("pPrntAsmblies", value);
    }
}

