package com.aalm.gl.model.common;

import java.sql.Date;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Jan 05 14:01:20 EET 2024
// ---------------------------------------------------------------------
public interface AalmGl extends ApplicationModule {
    void create_gl_assistance_from_tables(Integer vAccCode, String vTblName, Integer vOrgCode);

    void gl_posting(Integer vOrgCode, Integer vAccCode, String vCurrCode, Date vTrDate, float vTrDebit,
                    float vTrCredit);

    void update_original_gl_doc(Integer vOriginGlDocId, Integer vOriginOrgCode);

    Integer reverse_document(Integer vOrgCode, Integer vGlDocId);
}

