package com.aalm.pm.model.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jun 10 08:45:45 EEST 2026
// ---------------------------------------------------------------------
public interface AalmPm extends ApplicationModule {
    void delete_project(int pProjId);
}

