package com.aalm.master.model;

import com.aalm.master.model.common.AalmMaster;

import com.mysql.jdbc.PreparedStatement;

import java.sql.CallableStatement;
import java.sql.SQLException;

import oracle.jbo.JboException;
import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.DBTransactionImpl;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Aug 06 20:47:02 EEST 2025
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AalmMasterImpl extends ApplicationModuleImpl implements AalmMaster {
    /**
     * This is the default constructor (do not remove).
     */
    public AalmMasterImpl() {
    }

/**
 * Custom method for generating today record for logged user
 */
    public void createTodayAttendanceIfMissing(int userId) {
    DBTransactionImpl dbti = (DBTransactionImpl) getDBTransaction();
    CallableStatement stmnt = dbti.createCallableStatement(("call create_today_attendance(?);"),0);
    try {
        System.out.println("user is :"+userId);
        stmnt.setInt(1, userId);
        stmnt.execute();
      System.out.println("check done.++++++++");
        executeCommand("Commit");
    }catch (SQLException sqlerr) {
             System.out.println(" Today Attendance is not done--------");
        throw new JboException(sqlerr);
    } finally {
        try {
            if (stmnt != null) {
                stmnt.close();
            }
        } catch (SQLException closeerr) {
            throw new JboException(closeerr);
        }
    }
}

    /**
     * Container's getter for LanguageV.
     * @return LanguageV
     */
    public ViewObjectImpl getLanguageV() {
        return (ViewObjectImpl) findViewObject("LanguageV");
    }

    /**
     * Container's getter for OrgUsersV.
     * @return OrgUsersV
     */
    public ViewObjectImpl getOrgUsersV() {
        return (ViewObjectImpl) findViewObject("OrgUsersV");
    }

    /**
     * Container's getter for UserRolesMasterV.
     * @return UserRolesMasterV
     */
    public ViewObjectImpl getUserRolesMasterV() {
        return (ViewObjectImpl) findViewObject("UserRolesMasterV");
    }

    /**
     * Container's getter for UserRolesV.
     * @return UserRolesV
     */
    public ViewObjectImpl getUserRolesV() {
        return (ViewObjectImpl) findViewObject("UserRolesV");
    }

    /**
     * Container's getter for UserPermissionsV.
     * @return UserPermissionsV
     */
    public ViewObjectImpl getUserPermissionsV() {
        return (ViewObjectImpl) findViewObject("UserPermissionsV");
    }

    /**
     * Container's getter for SpecUserPermissionsV.
     * @return SpecUserPermissionsV
     */
    public ViewObjectImpl getSpecUserPermissionsV() {
        return (ViewObjectImpl) findViewObject("SpecUserPermissionsV");
    }

    /**
     * Container's getter for RoleMasterV.
     * @return RoleMasterV
     */
    public ViewObjectImpl getRoleMasterV() {
        return (ViewObjectImpl) findViewObject("RoleMasterV");
    }

    /**
     * Container's getter for RolesV.
     * @return RolesV
     */
    public ViewObjectImpl getRolesV() {
        return (ViewObjectImpl) findViewObject("RolesV");
    }

    /**
     * Container's getter for PermissionsV.
     * @return PermissionsV
     */
    public ViewObjectImpl getPermissionsV() {
        return (ViewObjectImpl) findViewObject("PermissionsV");
    }

    /**
     * Container's getter for SystemUsersV.
     * @return SystemUsersV
     */
    public ViewObjectImpl getSystemUsersV() {
        return (ViewObjectImpl) findViewObject("SystemUsersV");
    }

    /**
     * Container's getter for SysUsrControlOrgsV.
     * @return SysUsrControlOrgsV
     */
    public ViewObjectImpl getSysUsrControlOrgsV() {
        return (ViewObjectImpl) findViewObject("SysUsrControlOrgsV");
    }

    /**
     * Container's getter for SystUsrRolesMasterV.
     * @return SystUsrRolesMasterV
     */
    public ViewObjectImpl getSystUsrRolesMasterV() {
        return (ViewObjectImpl) findViewObject("SystUsrRolesMasterV");
    }

    /**
     * Container's getter for SystemParametersV.
     * @return SystemParametersV
     */
    public ViewObjectImpl getSystemParametersV() {
        return (ViewObjectImpl) findViewObject("SystemParametersV");
    }

    /**
     * Container's getter for VerifyResetPswrdUsersV.
     * @return VerifyResetPswrdUsersV
     */
    public ViewObjectImpl getVerifyResetPswrdUsersV() {
        return (ViewObjectImpl) findViewObject("VerifyResetPswrdUsersV");
    }

    /**
     * Container's getter for NonGrantedRolesSyssV.
     * @return NonGrantedRolesSyssV
     */
    public ViewObjectImpl getNonGrantedRolesSyssV() {
        return (ViewObjectImpl) findViewObject("NonGrantedRolesSyssV");
    }

    /**
     * Container's getter for NonGrantedSysFncnsV.
     * @return NonGrantedSysFncnsV
     */
    public ViewObjectImpl getNonGrantedSysFncnsV() {
        return (ViewObjectImpl) findViewObject("NonGrantedSysFncnsV");
    }

    /**
     * Container's getter for GrantedRolesV.
     * @return GrantedRolesV
     */
    public ViewObjectImpl getGrantedRolesV() {
        return (ViewObjectImpl) findViewObject("GrantedRolesV");
    }

    /**
     * Container's getter for GrantedPermissionsV.
     * @return GrantedPermissionsV
     */
    public ViewObjectImpl getGrantedPermissionsV() {
        return (ViewObjectImpl) findViewObject("GrantedPermissionsV");
    }

    /**
     * Container's getter for UserInOrgV.
     * @return UserInOrgV
     */
    public ViewObjectImpl getUserInOrgV() {
        return (ViewObjectImpl) findViewObject("UserInOrgV");
    }

    /**
     * Container's getter for UserAttendanceV.
     * @return UserAttendanceV
     */
    public ViewObjectImpl getUserAttendanceV() {
        return (ViewObjectImpl) findViewObject("UserAttendanceV");
    }

    /**
     * Container's getter for FkUserRolesMasterOrgUsers1VL1.
     * @return FkUserRolesMasterOrgUsers1VL1
     */
    public ViewLinkImpl getFkUserRolesMasterOrgUsers1VL1() {
        return (ViewLinkImpl) findViewLink("FkUserRolesMasterOrgUsers1VL1");
    }

    /**
     * Container's getter for FkUserRolesUserRolesMaster1VL1.
     * @return FkUserRolesUserRolesMaster1VL1
     */
    public ViewLinkImpl getFkUserRolesUserRolesMaster1VL1() {
        return (ViewLinkImpl) findViewLink("FkUserRolesUserRolesMaster1VL1");
    }

    /**
     * Container's getter for FkUserPermissionsUserRoles1VL1.
     * @return FkUserPermissionsUserRoles1VL1
     */
    public ViewLinkImpl getFkUserPermissionsUserRoles1VL1() {
        return (ViewLinkImpl) findViewLink("FkUserPermissionsUserRoles1VL1");
    }

    /**
     * Container's getter for FkRoleSystemsRoles1VL1.
     * @return FkRoleSystemsRoles1VL1
     */
    public ViewLinkImpl getFkRoleSystemsRoles1VL1() {
        return (ViewLinkImpl) findViewLink("FkRoleSystemsRoles1VL1");
    }

    /**
     * Container's getter for FkPermissionsRoles1VL1.
     * @return FkPermissionsRoles1VL1
     */
    public ViewLinkImpl getFkPermissionsRoles1VL1() {
        return (ViewLinkImpl) findViewLink("FkPermissionsRoles1VL1");
    }

    /**
     * Container's getter for FkUsersControlOrgsOrgUsers1VL1.
     * @return FkUsersControlOrgsOrgUsers1VL1
     */
    public ViewLinkImpl getFkUsersControlOrgsOrgUsers1VL1() {
        return (ViewLinkImpl) findViewLink("FkUsersControlOrgsOrgUsers1VL1");
    }

    /**
     * Container's getter for FkUserRolesMasterOrgUsers1VL2.
     * @return FkUserRolesMasterOrgUsers1VL2
     */
    public ViewLinkImpl getFkUserRolesMasterOrgUsers1VL2() {
        return (ViewLinkImpl) findViewLink("FkUserRolesMasterOrgUsers1VL2");
    }

    /**
     * Container's getter for GrantedSysToGrantedFncnsCVL1.
     * @return GrantedSysToGrantedFncnsCVL1
     */
    public ViewLinkImpl getGrantedSysToGrantedFncnsCVL1() {
        return (ViewLinkImpl) findViewLink("GrantedSysToGrantedFncnsCVL1");
    }

    /**
     * Container's getter for FkPermissionsRoles1VL2.
     * @return FkPermissionsRoles1VL2
     */
    public ViewLinkImpl getFkPermissionsRoles1VL2() {
        return (ViewLinkImpl) findViewLink("FkPermissionsRoles1VL2");
    }

    /**
     * Container's getter for FkUsersControlOrgsOrgUsers1VL2.
     * @return FkUsersControlOrgsOrgUsers1VL2
     */
    public ViewLinkImpl getFkUsersControlOrgsOrgUsers1VL2() {
        return (ViewLinkImpl) findViewLink("FkUsersControlOrgsOrgUsers1VL2");
    }

    /**
     * Container's getter for FkAttendanceUserVL1.
     * @return FkAttendanceUserVL1
     */
    public ViewLinkImpl getFkAttendanceUserVL1() {
        return (ViewLinkImpl) findViewLink("FkAttendanceUserVL1");
    }


    /**
     * Container's getter for AttendanceStatistics1.
     * @return AttendanceStatistics1
     */
    public ViewObjectImpl getAttendanceStatistics() {
        return (ViewObjectImpl) findViewObject("AttendanceStatistics");
    }

    /**
     * Container's getter for AttendanceToAttendanceStatisticsVL1.
     * @return AttendanceToAttendanceStatisticsVL1
     */
    public ViewLinkImpl getAttendanceToAttendanceStatisticsVL1() {
        return (ViewLinkImpl) findViewLink("AttendanceToAttendanceStatisticsVL1");
    }
}

