package com.aalm.center.model.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Sep 25 20:48:23 EET 2023
// ---------------------------------------------------------------------
public interface AalmCentral extends ApplicationModule {
    void add_item_structure(String origCol, String COLNAME);


    void create_items_from_item_variables_test();

    void create_items_from_variables(String catId, String unitId, Integer orgCode);

    void delete_items_from_item_variables_test();

    int validate_var_value(String v_val);
}

