package com.aalm.master.model.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Aug 06 21:07:05 EEST 2025
// ---------------------------------------------------------------------
public interface AalmMaster extends ApplicationModule {
    void createTodayAttendanceIfMissing(int userId);
}

