package com.aalm.hr.model;


import com.aalm.hr.model.common.AalmHr;

import java.sql.CallableStatement;
import java.sql.SQLException;

import oracle.jbo.JboException;
import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.DBTransactionImpl;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;

import org.eclipse.persistence.jpa.jpql.parser.DateTime;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Oct 24 08:25:50 EET 2025
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AalmHrImpl extends ApplicationModuleImpl implements AalmHr {
    /**
     * This is the default constructor (do not remove).
     */
    public AalmHrImpl() {
    }

    /**
     * Custom method for handling approval transaction action
     */
        public void sp_create_approval_transaction(
         int p_cycle_type_id
        ,int p_transaction_ref_id
        ,int p_requested_by
        ,int p_org_code
        ) {
        DBTransactionImpl dbti = (DBTransactionImpl) getDBTransaction();
        CallableStatement stmnt = dbti.createCallableStatement(("call sp_create_approval_transaction(?,?,?,?,?);"),0);
        try {
            System.out.println("Cycle ID :"+p_cycle_type_id);
            stmnt.setInt(1, p_cycle_type_id);
            stmnt.setInt(2, p_transaction_ref_id);
            stmnt.setInt(3, p_requested_by);
            stmnt.setInt(4, p_org_code);
            stmnt.setTimestamp(5, new java.sql.Timestamp(System.currentTimeMillis())); // p_action_date
            stmnt.execute();
        
          System.out.println("approval transaction created successfully.++++++++");
            executeCommand("Commit");
        }catch (SQLException sqlerr) {
                 System.out.println(" approval transaction is not done--------");
            throw new JboException(sqlerr);
        } finally {
            try {
                if (stmnt != null) {
                    stmnt.close();
                }
            } catch (SQLException closeerr) {
                throw new JboException(closeerr);
            }
        }
    }
    
    /**
     * Custom method for handling approval transaction action
     */
        public void sp_handle_approval_action(
         int p_trans_id
        ,int p_detail_id
        ,String p_action
        ,String p_comments
        ) {
        DBTransactionImpl dbti = (DBTransactionImpl) getDBTransaction();
        CallableStatement stmnt = dbti.createCallableStatement(("call sp_handle_approval_action(?,?,?,?,?);"),0);
        try {
            System.out.println("Trans ID :"+p_trans_id);
            stmnt.setInt(1, p_trans_id);
            stmnt.setInt(2, p_detail_id);
            stmnt.setString(3, p_action);
            stmnt.setTimestamp(4, new java.sql.Timestamp(System.currentTimeMillis())); // p_action_date
            stmnt.setString(5, p_comments);
            stmnt.execute();
        
          System.out.println("approval action updated successfully.++++++++");
            executeCommand("Commit");
        }catch (SQLException sqlerr) {
                 System.out.println(" approval is not done--------");
            throw new JboException(sqlerr);
        } finally {
            try {
                if (stmnt != null) {
                    stmnt.close();
                }
            } catch (SQLException closeerr) {
                throw new JboException(closeerr);
            }
        }
    }
    
    /**
     * Container's getter for JobsV.
     * @return JobsV
     */
    public ViewObjectImpl getJobsV() {
        return (ViewObjectImpl) findViewObject("JobsV");
    }

    /**
     * Container's getter for EmployeesV.
     * @return EmployeesV
     */
    public ViewObjectImpl getEmployeesV() {
        return (ViewObjectImpl) findViewObject("EmployeesV");
    }

    /**
     * Container's getter for EmployeesCRUDV.
     * @return EmployeesCRUDV
     */
    public ViewObjectImpl getEmployeesCRUDV() {
        return (ViewObjectImpl) findViewObject("EmployeesCRUDV");
    }

    /**
     * Container's getter for EmployeeJobHistoryV.
     * @return EmployeeJobHistoryV
     */
    public ViewObjectImpl getEmployeeJobHistoryV() {
        return (ViewObjectImpl) findViewObject("EmployeeJobHistoryV");
    }

    /**
     * Container's getter for EmployeesContractsV.
     * @return EmployeesContractsV
     */
    public ViewObjectImpl getEmployeesContractsV() {
        return (ViewObjectImpl) findViewObject("EmployeesContractsV");
    }

    /**
     * Container's getter for SystemParameters.
     * @return SystemParameters
     */
    public ViewObjectImpl getSystemParameters() {
        return (ViewObjectImpl) findViewObject("SystemParameters");
    }

    /**
     * Container's getter for BenefitTypesV.
     * @return BenefitTypesV
     */
    public ViewObjectImpl getBenefitTypesV() {
        return (ViewObjectImpl) findViewObject("BenefitTypesV");
    }

    /**
     * Container's getter for BonusTypesV.
     * @return BonusTypesV
     */
    public ViewObjectImpl getBonusTypesV() {
        return (ViewObjectImpl) findViewObject("BonusTypesV");
    }

    /**
     * Container's getter for DeductionTypesV.
     * @return DeductionTypesV
     */
    public ViewObjectImpl getDeductionTypesV() {
        return (ViewObjectImpl) findViewObject("DeductionTypesV");
    }

    /**
     * Container's getter for PunishmentTypesV.
     * @return PunishmentTypesV
     */
    public ViewObjectImpl getPunishmentTypesV() {
        return (ViewObjectImpl) findViewObject("PunishmentTypesV");
    }

    /**
     * Container's getter for VacationTypesV.
     * @return VacationTypesV
     */
    public ViewObjectImpl getVacationTypesV() {
        return (ViewObjectImpl) findViewObject("VacationTypesV");
    }

    /**
     * Container's getter for OrgUsersV.
     * @return OrgUsersV
     */
    public ViewObjectImpl getOrgUsersV() {
        return (ViewObjectImpl) findViewObject("OrgUsersV");
    }

    /**
     * Container's getter for AttendanceV.
     * @return AttendanceV
     */
    public ViewObjectImpl getAttendanceV() {
        return (ViewObjectImpl) findViewObject("AttendanceV");
    }

    /**
     * Container's getter for AttendanceStatisticsV.
     * @return AttendanceStatisticsV
     */
    public ViewObjectImpl getAttendanceStatisticsV() {
        return (ViewObjectImpl) findViewObject("AttendanceStatisticsV");
    }

    /**
     * Container's getter for AttendanceRulesV.
     * @return AttendanceRulesV
     */
    public ViewObjectImpl getAttendanceRulesV() {
        return (ViewObjectImpl) findViewObject("AttendanceRulesV");
    }

    /**
     * Container's getter for UserVacationsV.
     * @return UserVacationsV
     */
    public ViewObjectImpl getUserVacationsV() {
        return (ViewObjectImpl) findViewObject("UserVacationsV");
    }

    /**
     * Container's getter for EmployeeVacationsStatisticsV.
     * @return EmployeeVacationsStatisticsV
     */
    public ViewObjectImpl getEmployeeVacationsStatisticsV() {
        return (ViewObjectImpl) findViewObject("EmployeeVacationsStatisticsV");
    }

    /**
     * Container's getter for JobsTreeV.
     * @return JobsTreeV
     */
    public ViewObjectImpl getJobsTreeV() {
        return (ViewObjectImpl) findViewObject("JobsTreeV");
    }

    /**
     * Container's getter for JobsTreeChildV.
     * @return JobsTreeChildV
     */
    public ViewObjectImpl getJobsTreeChildV() {
        return (ViewObjectImpl) findViewObject("JobsTreeChildV");
    }

    /**
     * Container's getter for ApprovalTransactionDetailsVO.
     * @return ApprovalTransactionDetailsVO
     */
    public ViewObjectImpl getApprovalTransactionDetailsVO() {
        return (ViewObjectImpl) findViewObject("ApprovalTransactionDetailsVO");
    }

    /**
     * Container's getter for fk_EMPLOYEE_JOB_HISTORY_EMPLOYEES1VL1.
     * @return fk_EMPLOYEE_JOB_HISTORY_EMPLOYEES1VL1
     */
    public ViewLinkImpl getfk_EMPLOYEE_JOB_HISTORY_EMPLOYEES1VL1() {
        return (ViewLinkImpl) findViewLink("fk_EMPLOYEE_JOB_HISTORY_EMPLOYEES1VL1");
    }

    /**
     * Container's getter for FkAttendanceUserVL1.
     * @return FkAttendanceUserVL1
     */
    public ViewLinkImpl getFkAttendanceUserVL1() {
        return (ViewLinkImpl) findViewLink("FkAttendanceUserVL1");
    }

    /**
     * Container's getter for OrgUsersToAttendanceStatisticsVL1.
     * @return OrgUsersToAttendanceStatisticsVL1
     */
    public ViewLinkImpl getOrgUsersToAttendanceStatisticsVL1() {
        return (ViewLinkImpl) findViewLink("OrgUsersToAttendanceStatisticsVL1");
    }

    /**
     * Container's getter for OrgUsersToUserVacationsVL1.
     * @return OrgUsersToUserVacationsVL1
     */
    public ViewLinkImpl getOrgUsersToUserVacationsVL1() {
        return (ViewLinkImpl) findViewLink("OrgUsersToUserVacationsVL1");
    }

    /**
     * Container's getter for OrgUserToEmpVacationStatisticsVL1.
     * @return OrgUserToEmpVacationStatisticsVL1
     */
    public ViewLinkImpl getOrgUserToEmpVacationStatisticsVL1() {
        return (ViewLinkImpl) findViewLink("OrgUserToEmpVacationStatisticsVL1");
    }

    /**
     * Container's getter for JobsTreeSelfJoinCVL1.
     * @return JobsTreeSelfJoinCVL1
     */
    public ViewLinkImpl getJobsTreeSelfJoinCVL1() {
        return (ViewLinkImpl) findViewLink("JobsTreeSelfJoinCVL1");
    }

    /**
     * Container's getter for OrgUsersToApprovalTransactionsDetsCL1.
     * @return OrgUsersToApprovalTransactionsDetsCL1
     */
    public ViewLinkImpl getOrgUsersToApprovalTransactionsDetsCL1() {
        return (ViewLinkImpl) findViewLink("OrgUsersToApprovalTransactionsDetsCL1");
    }

    /**
     * Container's getter for EmployeeApprovalStatusV1.
     * @return EmployeeApprovalStatusV1
     */
    public ViewObjectImpl getEmployeeApprovalStatusV() {
        return (ViewObjectImpl) findViewObject("EmployeeApprovalStatusV");
    }

    /**
     * Container's getter for UserVacationToApprovalStatusCL1.
     * @return UserVacationToApprovalStatusCL1
     */
    public ViewLinkImpl getUserVacationToApprovalStatusCL1() {
        return (ViewLinkImpl) findViewLink("UserVacationToApprovalStatusCL1");
    }

    /**
     * Container's getter for EmployeeExtraJobsV1.
     * @return EmployeeExtraJobsV1
     */
    public ViewObjectImpl getEmployeeExtraJobsV() {
        return (ViewObjectImpl) findViewObject("EmployeeExtraJobsV");
    }

    /**
     * Container's getter for FkEmployeeExtraJobsEmployees1Link1.
     * @return FkEmployeeExtraJobsEmployees1Link1
     */
    public ViewLinkImpl getFkEmployeeExtraJobsEmployees1Link1() {
        return (ViewLinkImpl) findViewLink("FkEmployeeExtraJobsEmployees1Link1");
    }

    /**
     * Container's getter for EmployeeExtraJobsV1.
     * @return EmployeeExtraJobsV1
     */
    public ViewObjectImpl getEmployeeCrudExtraJobsV() {
        return (ViewObjectImpl) findViewObject("EmployeeCrudExtraJobsV");
    }

    /**
     * Container's getter for FkEmployeeExtraJobsEmployeesCrudLink1.
     * @return FkEmployeeExtraJobsEmployeesCrudLink1
     */
    public ViewLinkImpl getFkEmployeeExtraJobsEmployeesCrudLink1() {
        return (ViewLinkImpl) findViewLink("FkEmployeeExtraJobsEmployeesCrudLink1");
    }
}

